CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -O3
LDFLAGS = -lraylib -lGL -lm -lpthread -ldl -lrt -lX11

SRCS = main.cpp CDifferentialDrive.cpp CWheel.cpp CLoopReader.cpp CRender.cpp CRangeSensor.cpp CRobot.cpp CRoom.cpp CSegmentLoop.cpp CVecMath.cpp CSimulation.cpp CTrail.cpp CWallFollowerRobot.cpp
OBJS = $(SRCS:.cpp=.o)
TARGET = robot_sim

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)